# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Jekyll plugin tutorial
email: osfameron@cpan.org
description: >
  A brief series of blog posts about how to create and test plugins
  for the Jekyll static blog framework.
baseurl: "/jekyll-plugins-tutorial"
url: 'osfameron.github.io'
twitter_username: osfameron
github_username:  osfameron

# Build settings
markdown: kramdown
